Typescript error being thrown when running app
/usr/local/lib/node_modules/ts-node/src/index.ts:250
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS2468: Cannot find global value 'Promise'.
app.ts(46,14): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:250:12)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:358:40)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:545:11)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:430:43)